[package]
name = "The-Future-of-Mail"
author = "Ryan Matthews <etrigan976@gmail.com>"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/etrigan976/The-Future-of-Mail"
license = "MIT"

[dependencies]
nannou = "0.19"
bevy = "0.15.1"